version: '3.8'

services:
  yolo-camera-stream:
    build: .
    container_name: hailo_yolo_camera_stream
    volumes:
      - .:/workspace
      - /dev:/dev  # Access to camera devices
      - /tmp:/tmp  # Access to temp files for frame sharing
      - /home/cm5/yolo_models:/home/cm5/yolo_models  # Access to YOLO models
      - /usr/lib/python3/dist-packages:/usr/lib/python3/dist-packages  # Access to system Hailo packages
    environment:
      - PYTHONPATH=/workspace:/usr/lib/python3/dist-packages
    working_dir: /workspace
    network_mode: "host"  # Required to access UDP port 5000
    restart: unless-stopped
    command: ["python3", "/workspace/hailo_yolo_direct.py"]
    privileged: true  # Required for camera access

  web-stream-service:
    build: .
    container_name: hailo_web_stream_service
    volumes:
      - .:/workspace
      - /tmp:/tmp  # Access to processed frames
    environment:
      - PYTHONPATH=/workspace
    working_dir: /workspace
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: ["python3", "/workspace/web_stream_service_simple.py"]
    depends_on:
      - yolo-camera-stream 