version: '3.8'

services:
  yolo-camera-stream:
    build: .
    container_name: hailo_yolo_camera_stream
    volumes:
      - .:/workspace
      - /dev:/dev  # Access to camera devices
      - /dev/hailo0:/dev/hailo0  # Access to Hailo device
      - /tmp:/tmp  # Access to temp files for frame sharing
      - /home/cm5/yolo_models:/home/cm5/yolo_models  # Access to YOLO models
      - /usr/lib/python3/dist-packages:/usr/lib/python3/dist-packages:ro  # Access to system Hailo packages
      - /usr/local/lib/python3/dist-packages:/usr/local/lib/python3/dist-packages:ro  # Access to system Hailo packages
      - /usr/lib/python3.10/dist-packages:/usr/lib/python3.10/dist-packages:ro  # Access to Python 3.10 system packages
      - /usr/local/lib/python3.10/site-packages:/usr/local/lib/python3.10/site-packages:ro  # Access to Python 3.10 local packages
      - /usr/lib/python3.11/dist-packages:/usr/lib/python3.11/dist-packages:ro  # Access to Python 3.11 system packages (Hailo)
      - /usr/lib/python3:/usr/lib/python3:ro  # Access to system Python packages
      - /usr/local/lib/python3:/usr/local/lib/python3:ro  # Access to local Python packages
      - /usr/lib:/usr/lib:ro  # Access to system libraries
      - /usr/local/lib:/usr/local/lib:ro  # Access to local libraries
    environment:
      - PYTHONPATH=/workspace
      - LD_LIBRARY_PATH=/usr/lib:/usr/local/lib
      - UDP_PORT=5000  # Use UDP port 5000
    working_dir: /workspace
    ports:
      - "5000:5000/udp"  # Expose UDP port 5000
    restart: unless-stopped
    command: ["python3", "/workspace/hailo_yolo_main.py"]
    privileged: true  # Required for camera access

  simple-yolo-processor:
    build: .
    container_name: simple_yolo_processor
    volumes:
      - .:/workspace
      - /dev:/dev  # Access to camera devices
    environment:
      - PYTHONPATH=/workspace
      - UDP_PORT=5001  # Use UDP port 5001
    working_dir: /workspace
    ports:
      - "5001:5001/udp"  # Expose UDP port 5001
    restart: unless-stopped
    command: ["python3", "/workspace/simple_yolo_processor.py"]
    privileged: true  # Required for camera access

  hailo-test:
    build: .
    container_name: hailo_yolo_test
    volumes:
      - .:/workspace
      - /home/cm5/yolo_models:/home/cm5/yolo_models  # Access to YOLO models
      - /usr/lib/python3/dist-packages:/usr/lib/python3/dist-packages:ro  # Access to system Hailo packages
      - /usr/local/lib/python3/dist-packages:/usr/local/lib/python3/dist-packages:ro  # Access to system Hailo packages
    environment:
      - PYTHONPATH=/workspace
    working_dir: /workspace
    restart: "no"
    command: ["python3", "/workspace/test_hailo_basic.py"]
    privileged: true  # Required for device access

  opencv-test:
    build: .
    container_name: hailo_yolo_opencv_test
    volumes:
      - .:/workspace
      - /dev:/dev  # Access to camera devices
    environment:
      - PYTHONPATH=/workspace
    working_dir: /workspace
    restart: "no"
    command: ["python3", "/workspace/test_simple_opencv.py"]
    privileged: true  # Required for camera access

  web-stream-service:
    build: .
    container_name: hailo_yolo_web_stream
    volumes:
      - .:/workspace
      - /tmp:/tmp  # Access to temp files for frame sharing
    working_dir: /workspace
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: ["python3", "/workspace/web_stream_service_simple.py"] 